# Generated by Django 6.1.1 on 2026-10-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True, verbose_name='Chủ đề')),
                ('keywords', models.TextField(help_text='Nhập các từ khóa, phân cách nhau bởi dấu phẩy (,)', verbose_name='Từ khóa (cách nhau bởi dấu phẩy)')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
            ],
        ),
    ]
