# Generated by Django 6.1.1 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Câu hỏi chưa hiểu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian hỏi')),
            ],
            options={
                'verbose_name': 'Câu hỏi chưa hiểu',
                'verbose_name_plural': 'Các câu hỏi chưa hiểu',
            },
        ),
    ]
